FROM mcr.microsoft.com/devcontainers/python:3.11

# [Optional] Install OS packages here if needed
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>
